version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
